Update pre-start
Adding retry logic

diff --git a/jobs/sudo/templates/pre-start b/jobs/sudo/templates/pre-start
--- a/jobs/sudo/templates/pre-start
+++ b/jobs/sudo/templates/pre-start
@@ -1,2 +1,27 @@
 #!/bin/sh
-cp /var/vcap/packages/sudo-1.9.5p2/bin/sudo /usr/bin/sudo
+
+function fail {
+  echo $1 >&2
+  exit 1
+}
+
+function retry {
+  local n=1
+  local max=20
+  local delay=10
+  while true; do
+    "$@" && break || {
+      if [[ $n -lt $max ]]; then
+        ((n++))
+        echo "Command failed. Attempt $n/$max:"
+        sleep $delay;
+      else
+        fail "The command has failed after $n attempts."
+      fi
+    }
+  done
+}
+
+# source: https://unix.stackexchange.com/a/137639
+
+retry cp /var/vcap/packages/sudo-1.9.5p2/bin/sudo /usr/bin/sudo
